[PR 1] DEV-145 Multiple types of Measurements
HyperloopUPV-H8/ev-frontend pull request #55
Opened 2023-04-19 17:56 UTC by smorsua

The Measurements model has been split into multiple type to take advantage of a discriminated union. We discriminate using the type property. This makes each type more encapsulated because the enum and boolean type didn't require most of the properties.

2023-04-19 18:01 UTC, Losina24 requested changes

2023-04-19 18:01 UTC, Losina24 commented on src/GolangTypes.ts
> +export type GolangTypes = NumericType | Bool | Enum;
Commented in slack

2023-04-19 20:15 UTC, lipezaballa approved these changes

2023-04-23 11:06 UTC, Losina24 approved these changes

2023-04-23 14:07 UTC, jmaralo approved these changes

2023-04-23 14:07 UTC, merged